namespace YXH.Twain.Structure.Enum
{
    /// <summary>
    /// 支持纸张大小
    /// </summary>
    public enum SuportSize : ushort
    {
        TWSS_NONE,
        TWSS_A4LETTER,
        TWSS_B5LETTER,
        TWSS_USLETTER,
        TWSS_USLEGAL,
        TWSS_A5,
        TWSS_B4,
        TWSS_B6,
        TWSS_USLEDGER = 9,
        TWSS_USEXECUTIVE,
        TWSS_A3,
        TWSS_B3,
        TWSS_A6,
        TWSS_C4,
        TWSS_C5,
        TWSS_C6,
        TWSS_4A0,
        TWSS_2A0,
        TWSS_A0,
        TWSS_A1,
        TWSS_A2,
        TWSS_A7,
        TWSS_A8,
        TWSS_A9,
        TWSS_A10,
        TWSS_ISOB0,
        TWSS_ISOB1,
        TWSS_ISOB2,
        TWSS_ISOB5,
        TWSS_ISOB7,
        TWSS_ISOB8,
        TWSS_ISOB9,
        TWSS_ISOB10,
        TWSS_JISB0,
        TWSS_JISB1,
        TWSS_JISB2,
        TWSS_JISB3,
        TWSS_JISB4,
        TWSS_JISB6,
        TWSS_JISB7,
        TWSS_JISB8,
        TWSS_JISB9,
        TWSS_JISB10,
        TWSS_C0,
        TWSS_C1,
        TWSS_C2,
        TWSS_C3,
        TWSS_C7,
        TWSS_C8,
        TWSS_C9,
        TWSS_C10,
        TWSS_USSTATEMENT,
        TWSS_BUSINESSCARD,
        TWSS_MAXSIZE
    }

}
